# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker

services:
  - docker:dind

stages:
  - build_test

build_run:
  tags:
    - docker-builder
  stage: build_test
  script:
    - docker build -t gdd/blackstack .
    - mkdir docs; cp test/*pdf docs/
    - docker run -v $PWD/docs:app/pdf/docs gdd/blackstack 
    - ls ./docs/ocr/WH897R_29453_000452/tesseract/page_1.html

